test
├─ Inner Exceptions
│  ├─ 3 Exception
│  │  ├─ ex
│  │  │  
│  │  ├─ ex2
│  │  │  ├─ Inner Exception
│  │  │  │  ├─ inner
│  │  │  │  │  ├─ Inner Exception
│  │  │  │  │  │  ├─ inner2
│  │  │  │  │  │  │  
│  │  │  │  │  
│  │  │  
│  │  ├─ last
│  │  │  
│  ├─ 2 JLibAggregateException
│  │  ├─ child
│  │  │  ├─ Inner Exceptions
│  │  │  │  ├─ 2 Exception
│  │  │  │  │  ├─ child ex
│  │  │  │  │  │  
│  │  │  │  │  ├─ child ex 2
│  │  │  │  │  │  ├─ Inner Exception
│  │  │  │  │  │  │  ├─ child ex inner
│  │  │  │  │  │  │  │  
│  │  │  │  │  │  
│  │  │  │  ├─ 2 JLibAggregateException
│  │  │  │  │  ├─ inner3
│  │  │  │  │  │  ├─ Inner Exceptions
│  │  │  │  │  │  │  ├─ 1 Exception
│  │  │  │  │  │  │  │  ├─ sub child
│  │  │  │  │  │  │  │  │  second line
│  │  │  │  │  │  │  │  │  
│  │  │  │  │  │  
│  │  │  │  │  ├─ inner3
│  │  │  │  │  │  ├─ Inner Exceptions
│  │  │  │  │  │  │  ├─ 1 Exception
│  │  │  │  │  │  │  │  ├─ sub child2
│  │  │  │  │  │  │  │  │  second line2 with \n
│  │  │  │  │  │  │  │  │  
│  │  │  │  │  │  
│  │  │  
│  │  ├─ last child
│  │  │  ├─ Inner Exceptions
│  │  │  │  ├─ 1 Exception
│  │  │  │  │  ├─ last child exception
│  │  │  │  │  │  
│  │  │  

